import 'package:my_first_getx_app/constants/variables.dart';
import 'package:my_first_getx_app/data/model/expense_model.dart';

List<ExpenseModel> expenseList = [
  ExpenseModel(
    id: uuid.v4(),
    title: "Groceries",
    amount: 100.00,
    date: DateTime.now(),
    category: Category.food,
  ),
  ExpenseModel(
    id: uuid.v4(),
    title: "Flight",
    amount: 1200.00,
    date: DateTime.now(),
    category: Category.travel,
  ),
  ExpenseModel(
    id: uuid.v4(),
    title: "Concert",
    amount: 200.00,
    date: DateTime.now(),
    category: Category.leisure,
  ),
  ExpenseModel(
    id: uuid.v4(),
    title: "Rent",
    amount: 2000.00,
    date: DateTime.now(),
    category: Category.work,
  ),
  ExpenseModel(
    id: uuid.v4(),
    title: "Subscription",
    amount: 100.00,
    date: DateTime.now(),
    category: Category.work,
  ),
  ExpenseModel(
    id: uuid.v4(),
    title: "Grocery",
    amount: 150.00,
    date: DateTime.now(),
    category: Category.food,
  ),
  ExpenseModel(
    id: uuid.v4(),
    title: "Shopping",
    amount: 300.00,
    date: DateTime.now(),
    category: Category.leisure,
  ),
  ExpenseModel(
    id: uuid.v4(),
    title: "Flight",
    amount: 1200.00,
    date: DateTime.now(),
    category: Category.travel,
  ),
  ExpenseModel(
    id: uuid.v4(),
    title: "Concert",
    amount: 200.00,
    date: DateTime.now(),
    category: Category.leisure,
  ),
  ExpenseModel(
    id: uuid.v4(),
    title: "Rent",
    amount: 2000.00,
    date: DateTime.now(),
    category: Category.work,
  ),
  ExpenseModel(
    id: uuid.v4(),
    title: "Subscription",
    amount: 100.00,
    date: DateTime.now(),
    category: Category.work,
  ),
  ExpenseModel(
    id: uuid.v4(),
    title: "Grocery",
    amount: 150.00,
    date: DateTime.now(),
    category: Category.food,
  ),
  ExpenseModel(
    id: uuid.v4(),
    title: "Shopping",
    amount: 300.00,
    date: DateTime.now(),
    category: Category.leisure,
  ),
];
